name: Request Access to Private Home Lab Repository
description: Request access to the private HomeLab-ISSE-Collection repository
title: "[Access Request] <Your Name / Org>"
labels: ["access-request"]
body:
  - type: markdown
    attributes:
      value: |
        Thank you for your interest in the private Home Lab repository.
        Please complete the information below.

  - type: input
    id: name
    attributes:
      label: Name
      placeholder: Your full name
validations:
  required: true

  - type: input
    id: affiliation
    attributes:
      label: Affiliation / Organization
      placeholder: Company, school, or personal
validations:
  required: true

  - type: textarea
    id: reason
    attributes:
      label: Reason for Access
      description: Briefly describe why you’re requesting access.
      placeholder: What are you hoping to review or learn?
validations:
  required: true

Note: This request does not guarantee access. Submissions lacking sufficient detail may be declined.
