name: Request Access (Private Home Lab Repo)
description: Submit a request to view the private HomeLab-ISSE-Collection repository.
title: "[Access Request] <GitHub Username>"
labels: ["access-request"]

body:
  - type: markdown
    attributes:
      value: |
        Please complete the fields below.  
        **Do not include PII, email addresses, passwords, API keys, IP addresses, hostnames, or other sensitive (non-public) information.**

  - type: input
    id: contact
    attributes:
      label: GitHub Username
      description: Used only to grant repository access if approved.
      placeholder: "@githubhandle"
    validations:
      required: true

  - type: textarea
    id: justification
    attributes:
      label: Simple Access Justification
      description: One or two sentences is fine.
      placeholder: What are you hoping to review that is not in the public repository?
    validations:
      required: true

  - type: markdown
    attributes:
      value: |
        **Notice:** Applications are reviewed by **Reece Niemuth** on a need-to-know basis.  
        **Review time may vary, and access is not guaranteed.**
