name: Request Access (Private Home Lab Repo)
description: Submit a request to view the private HomeLab-ISSE-Collection repository.
title: "[Access Request] <Name / Org>"
labels: ["access-request"]

body:
  - type: markdown
    attributes:
      value: |
        Please complete the fields below.  
        **Do not include passwords, API keys, IP addresses, hostnames, or other sensitive details.**

  - type: input
    id: requester_name
    attributes:
      label: Name
      placeholder: First Last
    validations:
      required: true

  - type: input
    id: contact
    attributes:
      label: Email or GitHub Username
      placeholder: email@domain.com or @githubhandle
    validations:
      required: true

  - type: input
    id: affiliation
    attributes:
      label: Affiliation
      placeholder: Company / School / Personal
    validations:
      required: false

  - type: textarea
    id: justification
    attributes:
      label: Simple Access Justification
      description: One or two sentences is fine.
      placeholder: What are you hoping to review or learn?
    validations:
      required: true

  - type: markdown
    attributes:
      value: |
        **Notice:** Applications are reviewed by **Reece Niemuth** on a need-to-know basis. Review time may vary, and access is not guaranteed.
